master:
  healthcheckHttp: 8090
  varnamespace: wekii
  varappname: wordpress-site
  vartier: frontend
  varmaxUnavailable: 25 
  varmaxSurge: 25

wpingress:
  varurlservice: wekii.tk 
  varurlservice2: wekii.tk
  varbackendservname1: wordpress-site
  varbackendservport1: 443
  varbackendservname2: wordpress-site
  varbackendservport2: 443
  
wpservices:
  httpportname: 80
  httptargetport: 80
  httpport: 80
  httpsportname: 443
  httpsport: 443
  httpstargetport: 443
  fastcgiportname: 9000
  fastsport: 9000
  fasttargetport: 9000
  
wpimage:
  repository: "miguelburgos/wekii"
  imagePull: 
    - name: fabrdockerhubregcred
  tag: dev-7
  pullPolicy: Always

wpcontainer:
  name: app
  replicaCount: 1
  port: 8290

wpenvFrom:
  - configMapRef:
      name: wordpress-configmap

wpresources:
  requests:
    memory: "ssds"

wpvolumes:
  - name: nginxconf
    configMap:
      name: nginxthroughpass
      defaultMode: 256
      optional: false
