---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.master.vardbname }}-deployment
  namespace: {{ .Values.master.varnamespace }}
  labels:
    app: {{ .Values.master.varappname }}
spec:
  replicas: {{ .Values.wpdbcontainer.replicaCount }}
  revisionHistoryLimit: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: {{ .Values.master.varappname }}
      tier: {{ .Values.master.vartier }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.master.varmaxUnavailable }}
      maxSurge: {{ .Values.master.varmaxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.master.varappname }}
        tier: {{ .Values.master.vartier }}
    spec:
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /var/www/example.com/database2/data
            type: ''
        - name: mysql-persistent-storage1
          hostPath:
            path: /var/www/example.com/database2/initdb.d
            type: ''
      containers:
        - name: {{ .Values.wpdbcontainer.name }}
          image: {{ .Values.wpdbimage.repository }}:{{ .Values.wpdbimage.tag }}
          args:
            - '--ignore-db-dir=lost+found'
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: bpsconsu_wekiidb2
            - name: MYSQL_USER
              value: wpuser
            - name: MYSQL_PASSWORD
              value: g#6Igm5u5bamwLJHSm
          ports:
            - name: {{ .Values.wpdbcontainer.portname }}
              containerPort: {{ .Values.wpdbcontainer.port }}
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.wpdbresources.limits.cpu }}
              memory: {{ .Values.wpdbresources.limits.memory }}
            requests:
              cpu: {{ .Values.wpdbresources.requests.cpu }}
              memory: {{ .Values.wpdbresources.requests.memory }}
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-persistent-storage1
              mountPath: /docker-entrypoint-initdb.d
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.wpdbimage.pullPolicy }}
