kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.wpconfigmap.nginxthroughpassname }}
  namespace: {{ .Values.master.varnamespace }}
data:
  default.conf: |
    server_names_hash_bucket_size 64;

    fastcgi_cache_path /etc/nginx/cache levels=1:2 keys_zone=MYAPP:100m
    inactive=60m;

    fastcgi_cache_key "$scheme$request_method$host$request_uri";
    
    server {
            listen 443  ssl default_server;
            ssl_certificate     /root/normal.pem;
            ssl_certificate_key /root/wekiitk_private_chained.key;
             root /var/www/html;
            server_name _;
            index index.php;
            gzip on;
            gzip_min_length 1000;
            gzip_buffers 4 32k;
            gzip_proxied any;
            gzip_types text/plain application/javascript application/x-javascript text/javascript 
            text/xml text/css;
            gzip_vary on;
            gzip_disable "MSIE [1-6]\.(?!.*SV1)";
            sendfile            on;
            tcp_nopush          on;
            tcp_nodelay         on;
            keepalive_timeout   65;
            types_hash_max_size 2048;

            location / {
            #try_files $uri $uri/ /index.php?$args =404;
            try_files $uri $uri/ /index.php?q=$uri&$args;
            #CORS ENABLED
             if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            #
            # Custom headers and headers various browsers *should* be OK with but aren't
            #
            #add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If Modified-Since,Cache-Control,Content-Type,Range';
            #
            # Tell client that this pre-flight info is valid for 20 days
            #
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
             }
            }

            error_page 404 /404.html;
            error_page 500 502 503 504 /50x.html;
            
             location ~ \.php$ {
                try_files $uri /index.php?$args =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_buffers 256 128k;
                fastcgi_connect_timeout 300s;
                fastcgi_send_timeout 300s;
                fastcgi_read_timeout 300s;
                fastcgi_index index.php;
                include fastcgi_params;

           fastcgi_cache MYAPP;
            fastcgi_cache_valid 200 60m;

                fastcgi_param   PATH_INFO       $fastcgi_path_info;
                fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
            }
            location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            expires 365d;
             }
        }
